# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/CodWork1/CoDwork/CoDwork.cache/wt [current_project]
set_property parent.project_path D:/CodWork1/CoDwork/CoDwork.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/CodWork1/CoDwork/CoDwork.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files d:/PoDWork/test.coe
read_verilog -library xil_defaultlib {
  D:/CodWork1/CoDwork/CoDwork.srcs/sources_1/imports/PoDWork/FPGATop/MIO_BUS.v
  D:/CodWork1/CoDwork/CoDwork.srcs/sources_1/imports/PoDWork/FPGATop/Multi_CH32.v
  D:/CodWork1/CoDwork/CoDwork.srcs/sources_1/imports/PoDWork/PCPU/ctrl_encode_def.v
  D:/CodWork1/CoDwork/CoDwork.srcs/sources_1/imports/PoDWork/PCPU/alu.v
  D:/CodWork1/CoDwork/CoDwork.srcs/sources_1/imports/PoDWork/FPGATop/clk_div.v
  D:/CodWork1/CoDwork/CoDwork.srcs/sources_1/imports/PoDWork/PCPU/dffe32.v
  D:/CodWork1/CoDwork/CoDwork.srcs/sources_1/imports/PoDWork/FPGATop/dm.v
  D:/CodWork1/CoDwork/CoDwork.srcs/sources_1/imports/PoDWork/PCPU/mux2x32.v
  D:/CodWork1/CoDwork/CoDwork.srcs/sources_1/imports/PoDWork/PCPU/mux2x5.v
  D:/CodWork1/CoDwork/CoDwork.srcs/sources_1/imports/PoDWork/PCPU/mux4x32.v
  D:/CodWork1/CoDwork/CoDwork.srcs/sources_1/imports/PoDWork/PCPU/pipecpu.v
  D:/CodWork1/CoDwork/CoDwork.srcs/sources_1/imports/PoDWork/PCPU/pipedereg.v
  D:/CodWork1/CoDwork/CoDwork.srcs/sources_1/imports/PoDWork/PCPU/pipeemreg.v
  D:/CodWork1/CoDwork/CoDwork.srcs/sources_1/imports/PoDWork/PCPU/pipeexe.v
  D:/CodWork1/CoDwork/CoDwork.srcs/sources_1/imports/PoDWork/PCPU/pipeid.v
  D:/CodWork1/CoDwork/CoDwork.srcs/sources_1/imports/PoDWork/PCPU/pipeidcu.v
  D:/CodWork1/CoDwork/CoDwork.srcs/sources_1/imports/PoDWork/PCPU/pipeif.v
  D:/CodWork1/CoDwork/CoDwork.srcs/sources_1/imports/PoDWork/PCPU/pipeir.v
  D:/CodWork1/CoDwork/CoDwork.srcs/sources_1/imports/PoDWork/PCPU/pipemwreg.v
  D:/CodWork1/CoDwork/CoDwork.srcs/sources_1/imports/PoDWork/PCPU/pipepc.v
  D:/CodWork1/CoDwork/CoDwork.srcs/sources_1/imports/PoDWork/PCPU/regfile.v
  D:/CodWork1/CoDwork/CoDwork.srcs/sources_1/imports/PoDWork/FPGATop/seg7x16.v
  D:/CodWork1/CoDwork/CoDwork.srcs/sources_1/imports/PoDWork/FPGATop/SCPU_Top.v
}
read_ip -quiet d:/CodWork1/CoDwork/CoDwork.srcs/sources_1/ip/imem/imem.xci
set_property used_in_implementation false [get_files -all d:/CodWork1/CoDwork/CoDwork.srcs/sources_1/ip/imem/imem_ooc.xdc]
set_property is_locked true [get_files d:/CodWork1/CoDwork/CoDwork.srcs/sources_1/ip/imem/imem.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/CodWork1/CoDwork/CoDwork.srcs/constrs_1/imports/PoDWork/Nexys4DDR_CPU.xdc
set_property used_in_implementation false [get_files D:/CodWork1/CoDwork/CoDwork.srcs/constrs_1/imports/PoDWork/Nexys4DDR_CPU.xdc]


synth_design -top IP2SOC_Top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef IP2SOC_Top.dcp

catch { report_utilization -file IP2SOC_Top_utilization_synth.rpt -pb IP2SOC_Top_utilization_synth.pb }
